"""AgentSpec — declarative agent definition with YAML/JSON serialization.

An AgentSpec is the complete, self-contained definition of an agent:
graph (nodes + edges), triggers, config, resources, and metadata.

One YAML file = one agent. Export it, send it to another server, import it.
"""

from __future__ import annotations

import json
import uuid
from pathlib import Path
from typing import Any

import yaml
from pydantic import BaseModel, Field, model_validator

from datamirai_engine.core.enums import Backoff, OnFailure, TriggerType
from datamirai_engine.core.graph import EdgeDef, GraphDef, NodeDef


# --- Sub-models ---


class AgentNodeSpec(BaseModel):
    """Node within an agent spec. Maps to NodeDef."""

    id: str
    tool_type: str
    version: str = "1.0.0"
    config: dict[str, Any] = Field(default_factory=dict)
    position: dict[str, float] = Field(default_factory=lambda: {"x": 0.0, "y": 0.0})


class AgentEdgeSpec(BaseModel):
    """Edge within an agent spec. Maps to EdgeDef.

    FEAT-034: id is optional — auto-generated by GraphDef if omitted.
    """

    id: str = ""
    source: str
    target: str
    condition: dict[str, Any] | None = None
    data_map: dict[str, str] | None = None


class AgentGraphSpec(BaseModel):
    """Inline graph definition inside an agent spec."""

    nodes: list[AgentNodeSpec] = Field(default_factory=list)
    edges: list[AgentEdgeSpec] = Field(default_factory=list)


class AgentRetryConfig(BaseModel):
    """Retry policy at agent level."""

    max_retries: int = 3
    backoff: str | Backoff = Backoff.EXPONENTIAL
    on_failure: str | OnFailure = OnFailure.STOP


class AgentHookSpec(BaseModel):
    """Hook definition within agent config."""

    handler: str  # function name or module.path
    filter: str | None = None  # glob pattern for tool_type (e.g., "ai/*")


class AgentMcpServerSpec(BaseModel):
    """MCP server reference within agent config."""

    name: str
    transport: str = "stdio"  # stdio | http
    command: str | None = None  # for stdio
    args: list[str] = Field(default_factory=list)  # for stdio
    url: str | None = None  # for http
    credential_ref: str | None = None  # vault credential reference


class AgentConfig(BaseModel):
    """Top-level agent configuration."""

    max_iterations: int = 50
    retry: AgentRetryConfig = Field(default_factory=AgentRetryConfig)
    timeout_ms: int = 60000
    hooks: dict[str, list[AgentHookSpec]] = Field(default_factory=dict)
    mcp_servers: list[AgentMcpServerSpec] = Field(default_factory=list)
    vault_refs: list[dict[str, str]] = Field(default_factory=list)


class AgentTriggerSpec(BaseModel):
    """Trigger definition within an agent spec."""

    type: str | TriggerType
    path: str | None = None
    method: str | None = None
    auth: str | None = None
    interval_seconds: int | None = None
    cron: str | None = None
    event_type: str | None = None
    source: str | None = None
    input_form: list[dict[str, Any]] | None = None

    def to_runtime_dict(self) -> dict[str, Any]:
        """Convert to the dict format AgentRuntime expects."""
        d: dict[str, Any] = {"type": self.type}
        for field_name in (
            "path", "method", "auth", "interval_seconds",
            "cron", "event_type", "source", "input_form",
        ):
            val = getattr(self, field_name)
            if val is not None:
                d[field_name] = val
        return d


# --- Main AgentSpec ---


class AgentSpec(BaseModel):
    """Complete, self-contained agent definition.

    Includes the graph inline (nodes + edges), triggers, config,
    resource references, and metadata. Serializes to/from YAML and JSON.
    """

    name: str
    description: str = ""
    version: str = "v1"
    agent_type: str = "managed"  # managed | live
    system_prompt: str = ""
    graph: AgentGraphSpec = Field(default_factory=AgentGraphSpec)
    triggers: list[AgentTriggerSpec] = Field(default_factory=list)
    config: AgentConfig = Field(default_factory=AgentConfig)
    resources: list[str] = Field(default_factory=list)
    metadata: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _validate_graph_refs(self) -> AgentSpec:
        """Validate that edges reference existing nodes."""
        node_ids = {n.id for n in self.graph.nodes}

        # Duplicate node IDs
        all_ids = [n.id for n in self.graph.nodes]
        dupes = {nid for nid in all_ids if all_ids.count(nid) > 1}
        if dupes:
            raise ValueError(f"Duplicate node IDs: {dupes}")

        # Auto-generate missing edge IDs (FEAT-034 / API-02)
        seen_pairs: dict[str, int] = {}
        new_edges: list[AgentEdgeSpec] = []
        for edge in self.graph.edges:
            if not edge.id:
                pair_key = f"{edge.source}__{edge.target}"
                count = seen_pairs.get(pair_key, 0) + 1
                seen_pairs[pair_key] = count
                auto_id = pair_key if count == 1 else f"{pair_key}__{count}"
                edge = edge.model_copy(update={"id": auto_id})
            new_edges.append(edge)
        object.__setattr__(self.graph, "edges", new_edges)

        # Duplicate edge IDs (after auto-gen)
        edge_ids = [e.id for e in self.graph.edges]
        edge_dupes = {eid for eid in edge_ids if edge_ids.count(eid) > 1}
        if edge_dupes:
            raise ValueError(f"Duplicate edge IDs: {edge_dupes}")

        # Edge references
        for edge in self.graph.edges:
            if edge.source not in node_ids:
                raise ValueError(
                    f"Edge '{edge.id}' references non-existent source node '{edge.source}'"
                )
            if edge.target not in node_ids:
                raise ValueError(
                    f"Edge '{edge.id}' references non-existent target node '{edge.target}'"
                )

        return self

    # --- Serialization ---

    def to_dict(self) -> dict[str, Any]:
        """Serialize to a plain dict (JSON-compatible)."""
        return self.model_dump(exclude_none=True)

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> AgentSpec:
        """Create from a plain dict."""
        return cls.model_validate(data)

    def to_yaml(self) -> str:
        """Serialize to YAML string."""
        return yaml.dump(
            self.to_dict(),
            default_flow_style=False,
            sort_keys=False,
            allow_unicode=True,
        )

    @classmethod
    def from_yaml(cls, yaml_source: str) -> AgentSpec:
        """Parse YAML string or file path into AgentSpec.

        FEAT-034: accepts both a YAML string and a file path.
        """
        # If it looks like a file path, read it
        if "\n" not in yaml_source and (
            yaml_source.endswith(".yaml") or yaml_source.endswith(".yml")
        ):
            path = Path(yaml_source)
            if path.exists():
                yaml_source = path.read_text(encoding="utf-8")
        data = yaml.safe_load(yaml_source)
        if not isinstance(data, dict):
            raise ValueError("YAML must be a mapping at the top level")
        return cls.from_dict(data)

    def to_json(self, path: str | None = None, indent: int = 2) -> str:
        """Serialize to JSON string. Optionally write to file.

        FEAT-034: JSON is the canonical format.
        """
        json_str = json.dumps(
            self.to_dict(), indent=indent, ensure_ascii=False, default=str,
        )
        if path:
            Path(path).write_text(json_str, encoding="utf-8")
        return json_str

    @classmethod
    def from_json(cls, json_source: str) -> AgentSpec:
        """Parse JSON string or file path into AgentSpec.

        FEAT-034: accepts both a JSON string and a file path.
        """
        if "\n" not in json_source and json_source.endswith(".json"):
            path = Path(json_source)
            if path.exists():
                json_source = path.read_text(encoding="utf-8")
        data = json.loads(json_source)
        if not isinstance(data, dict):
            raise ValueError("JSON must be an object at the top level")
        return cls.from_dict(data)

    @classmethod
    def from_file(cls, path: str) -> AgentSpec:
        """Load from file — auto-detects format by extension.

        Supports .yaml, .yml, .json
        """
        p = Path(path)
        content = p.read_text(encoding="utf-8")
        if p.suffix in (".yaml", ".yml"):
            return cls.from_yaml(content)
        elif p.suffix == ".json":
            return cls.from_json(content)
        else:
            raise ValueError(f"Unsupported file extension: {p.suffix}")

    async def run(
        self,
        inputs: dict[str, Any] | None = None,
        *,
        context: Any = None,
        entry_node_id: str | None = None,
    ) -> Any:
        """Quick-run: execute this agent spec directly.

        FEAT-034: The simplest possible path — 2 lines:
            agent = AgentSpec.from_yaml("agent.yaml")
            result = await agent.run({"query": "hello"})
        """
        from datamirai_engine.core.runner import GraphRunner

        graph = self.to_graph()

        # Auto-detect entry node: first trigger or first node
        if entry_node_id is None:
            for node in graph.nodes:
                if node.tool_type.startswith("trigger/"):
                    entry_node_id = node.id
                    break
            if entry_node_id is None and graph.nodes:
                entry_node_id = graph.nodes[0].id
        if entry_node_id is None:
            raise ValueError("No nodes in graph — cannot determine entry node")

        # Default context if none provided
        if context is None:
            from datamirai_engine.resources.context import SimpleExecutionContext

            context = SimpleExecutionContext.default()

        # Inject trigger inputs into context state
        initial_state = None
        if inputs:
            initial_state = {entry_node_id: inputs}

        runner = GraphRunner.default()
        return await runner.run(
            graph, context=context, entry_node_id=entry_node_id,
            initial_state=initial_state,
        )

    # --- Conversion to runtime types ---

    def to_graph(self, graph_id: str | None = None) -> GraphDef:
        """Convert the inline graph to a GraphDef ready for execution."""
        gid = graph_id or str(uuid.uuid4())[:8]
        nodes = [
            NodeDef(
                id=n.id,
                tool_type=n.tool_type,
                version=n.version,
                config=n.config,
                position=n.position,
            )
            for n in self.graph.nodes
        ]
        edges = [
            EdgeDef(
                id=e.id,
                source=e.source,
                target=e.target,
                condition=e.condition,
                data_map=e.data_map,
            )
            for e in self.graph.edges
        ]
        return GraphDef(
            id=gid,
            name=self.name,
            version=self.version,
            nodes=nodes,
            edges=edges,
            metadata=dict(self.metadata),
        )

    def to_triggers_list(self) -> list[dict[str, Any]]:
        """Convert triggers to the list[dict] format AgentRuntime expects."""
        return [t.to_runtime_dict() for t in self.triggers]
